angular.module("admin")
    // 认证管理常理常量
    //客户服务
    .constant('customerConstant', {
        status:[
            {
                type:0,
                name:'冻结'
            }
            ,
            {
                type:1,
                name:'解冻'
            }
        ],
        lockStatus:[
            {
                type:0,
                name:'冻结'
            }
            ,
            {
                type:1,
                name:'正常'
            }
        ],
        buyStatus:[
            {
                type:0,
                name:'未付费'
            }
            ,
            {
                type:1,
                name:'已付费'
            }
        ],
        examineStatus:[
            {
                type:0,
                name:'未审核'
            }
            ,
            {
                type:1,
                name:'通过'
            }
            ,
            {
                type:2,
                name:'未通过'
            }
        ],
        personType:[
            {
                type:1,
                name:'所有人'
            },
            {
                type:2,
                name:'所有已付费'
            },
            {
                type:3,
                name:'所有未付费'
            }
        ],
        sendStatus:[
            {
                type:0,
                name:'暂不发送'
            },
            {
                type:1,
                name:'已发送'
            },
            {
                type:2,
                name:'定时发送'
            }
        ],
        resArray:[
            {
                name:'兽医人数',
                value:''
            },
            {
                name:'股东1',
                value:''
            },
            {
                name:'股东2',
                value:''
            }
        ]

    })
    //设备模块服务
    .constant('deviceConstant', {
        status:[
            {
                type:0,
                name:'下架'
            }
            ,
            {
                type:1,
                name:'上架'
            }
        ],
        examineStatus:[
            {
                type:0,
                name:'未审核'
            }
            ,
            {
                type:1,
                name:'通过'
            }
            ,
            {
                type:1,
                name:'未通过'
            }
        ]
        ,overdueStatus:[
            {
                type:0,
                name:'否'
            }
            ,
            {
                type:1,
                name:'是'
            }
        ] ,prepayment:[

            {
                type:0,
                name:'未审核'
            }
            ,
            {
                type:1,
                name:'已通过'
            },
            {
                type:2,
                name:'全部'
            }
        ]
    })

    .constant("dealWay",[
        {id:0,name:'支付宝'},
        {id:1,name:'微信'}
    ])

    .constant("freezedStatus",{
        0:'正常',
        1:'冻结'
    })
    .constant("changeFreezedStatus",{
        0:'冻结',
        1:'正常'
    })
    .constant("approvedStatus",{
        1:'未认证',
        2:'已认证',
        3:'已拒绝',
        4:'已撤销'
    })
    .constant("dealType",{
        0:'方案支付'
    })
    .constant("dealStatus",{
        '-1':'订单失效',
        0:'付款失败',
        1:'付款成功',
        2:'待付款'
    })
    .constant("contentStatus",{
        1:'已上线',
        2:'草稿'
    })
    .constant("messageStatus",{
        0:'草稿',
        1:'已发送',
        2:'即将发送'
    })
;


